//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeydansWebSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeydansDBEntities : DbContext
    {
        public BeydansDBEntities()
            : base("name=BeydansDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAbout> tblAbout { get; set; }
        public virtual DbSet<tblActivities> tblActivities { get; set; }
        public virtual DbSet<tblAwards> tblAwards { get; set; }
        public virtual DbSet<tblContact> tblContact { get; set; }
        public virtual DbSet<tblHeader> tblHeader { get; set; }
        public virtual DbSet<tblPicture> tblPicture { get; set; }
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblProperties> tblProperties { get; set; }
    }
}
