//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeydansWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAwards
    {
        public System.Guid Id { get; set; }
        public string AwardName { get; set; }
        public string AwardDescription { get; set; }
        public string AwardPicture { get; set; }
    }
}
