//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeydansWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordHashKey { get; set; }
        public Nullable<System.DateTime> LastVisitedDate { get; set; }
    }
}
